### ISSUE TITLE
Youtube video download not working..

### ISSUE THREAD

**Issue by vincetota** [ShimmyMySherbet/YoutubeDownloader#4]
Hello
if I try to download a single youtube video, the app crashes...
If I try to download an entire playlist, it works..
Please can you check?

**Comment by ShimmyMySherbet** [comment]
This app has been deprecated and surpassed by my new project Musix Downloader.
This new app is significantly more performant and will support the development of multi-platform apps.

This new app does not have a GUI app yet, only a test console. But if you still want to check it out, you can see it here: https://github.com/ShimmyMySherbet/MusixDownloader.

**Comment by ShimmyMySherbet** [comment]
@vincetota Are you just after a GUI Youtube & Spotify music downloader?
